---
- name: Remove workers from OCP cluster
  hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
    - vars/all.yml
    - vars/vault.yml
    - vars/idm.yml
    - vars/kvm_host.yml
    - vars/ocp4.yml

  tasks:
  - name: remove OpenShift 4 bootstrap webserver
    import_role:
      name: ocp4-bootstrap-webserver
      tasks_from: main.yml
    tags: [ webserver ]

